// Nomes dos comandos Tauri (invoke) — único ponto de definição (spec §4.2).
export const IPC = {
  SCAN_LIBRARY: "scan_library",
  RESCAN_ALL: "rescan_all",
  GET_COLLECTIONS: "get_collections",
  GET_COLLECTION_DETAIL: "get_collection_detail",
  GET_VIDEO: "get_video",
  GET_CONTINUE_WATCHING: "get_continue_watching",
  GET_LIBRARY_ROOTS: "get_library_roots",
  GET_SETTINGS: "get_settings",
  SET_AUTO_SKIP_INTRO: "set_auto_skip_intro",
  GET_INTRO_MARKER: "get_intro_marker",
  SET_INTRO_MARKER: "set_intro_marker",
  ANALYZE_INTRO: "analyze_intro",
  CANCEL_INTRO_ANALYSIS: "cancel_intro_analysis",
  ACCEPT_INTRO_SUGGESTION: "accept_intro_suggestion",
  PLAY_VIDEO: "play_video",
  TOGGLE_PAUSE: "toggle_pause",
  SEEK: "seek",
  GET_CURRENT_POSITION: "get_current_position",
  GET_DURATION: "get_duration",
  SET_VOLUME: "set_volume",
  GET_TRACKS: "get_tracks",
  SET_AUDIO_TRACK: "set_audio_track",
  SET_SUBTITLE_TRACK: "set_subtitle_track",
  GET_PREVIEW_FRAME: "get_preview_frame",
  SET_PLAYBACK_RATE: "set_playback_rate",
  SET_AUDIO_DELAY: "set_audio_delay",
  SET_SUBTITLE_DELAY: "set_subtitle_delay",
  SET_VIDEO_WATCHED: "set_video_watched",
  REMOVE_LIBRARY_ROOT: "remove_library_root",
  GENERATE_EPISODE_THUMBNAILS: "generate_episode_thumbnails",
  CANCEL_EPISODE_THUMBNAILS: "cancel_episode_thumbnails",
  GENERATE_EPISODE_THUMBNAIL: "generate_episode_thumbnail",
  GET_EPISODE_THUMBNAIL: "get_episode_thumbnail",
  SET_COLLECTION_THUMBNAILS_VISIBLE: "set_collection_thumbnails_visible",
  STOP_PLAYBACK: "stop_playback",
  REMOVE_VIDEO_FROM_LIBRARY: "remove_video_from_library",
  DELETE_VIDEO_FILE: "delete_video_file",
  REMOVE_COLLECTION_FROM_LIBRARY: "remove_collection_from_library",
  DELETE_COLLECTION_FILES: "delete_collection_files",
  PREVIEW_EPISODE_NAMES: "preview_episode_names",
  APPLY_EPISODE_NAMES: "apply_episode_names",
  SET_VIDEO_DISPLAY_NAME: "set_video_display_name",
  PREVIEW_RENAME: "preview_rename",
  APPLY_RENAME: "apply_rename",
  SET_COLLECTION_TITLE: "set_collection_title",
  SET_COLLECTION_TYPE: "set_collection_type",
  MERGE_COLLECTION_INTO: "merge_collection_into",
  GENERATE_COLLECTION_POSTER: "generate_collection_poster",
  GET_COLLECTION_POSTER: "get_collection_poster",
  OPEN_PLAYER: "open_player",
  CLOSE_PLAYER: "close_player",
  SET_PLAYER_FULLSCREEN: "set_player_fullscreen",
} as const;

export type IpcCommand = (typeof IPC)[keyof typeof IPC];
