// Camada única de acesso ao backend — todo invoke passa por aqui, tipado.

import { invoke } from "@tauri-apps/api/core";
import { IPC } from "./constants/ipc.constants";
import type { CollectionCard, CollectionDetail, CollectionType, ContinueWatchingItem, DeleteOutcome, EpisodeNamePlanItem, IntroMarker, IntroSuggestion, LibraryRoot, PlaybackStartInfo, RenameOutcome, RenamePlanItem, ScanSummary, TrackMenu, UserSettings, VideoRow } from "./types";

export const api = {
  scanLibrary: (rootPath: string) => invoke<ScanSummary>(IPC.SCAN_LIBRARY, { rootPath }),
  rescanAll: () => invoke<ScanSummary>(IPC.RESCAN_ALL),
  getCollections: () => invoke<CollectionCard[]>(IPC.GET_COLLECTIONS),
  getCollectionDetail: (collectionId: number) => invoke<CollectionDetail>(IPC.GET_COLLECTION_DETAIL, { collectionId }),
  getVideo: (videoId: number) => invoke<VideoRow | null>(IPC.GET_VIDEO, { videoId }),
  getContinueWatching: () => invoke<ContinueWatchingItem[]>(IPC.GET_CONTINUE_WATCHING),
  getLibraryRoots: () => invoke<LibraryRoot[]>(IPC.GET_LIBRARY_ROOTS),
  getSettings: () => invoke<UserSettings>(IPC.GET_SETTINGS),
  setAutoSkipIntro: (enabled: boolean) => invoke<void>(IPC.SET_AUTO_SKIP_INTRO, { enabled }),
  getIntroMarker: (videoId: number) => invoke<IntroMarker | null>(IPC.GET_INTRO_MARKER, { videoId }),
  setIntroMarker: (collectionId: number, seasonId: number | null, startSeconds: number, endSeconds: number) => invoke<void>(IPC.SET_INTRO_MARKER, { collectionId, seasonId, startSeconds, endSeconds }),
  analyzeIntro: (request: { collectionId: number; videoIds: number[]; maxSeconds: number; sampleIntervalSeconds: number }) => invoke<IntroSuggestion[]>(IPC.ANALYZE_INTRO, { request }),
  cancelIntroAnalysis: () => invoke<void>(IPC.CANCEL_INTRO_ANALYSIS),
  acceptIntroSuggestion: (videoId: number, startSeconds: number, endSeconds: number, confidence: number) => invoke<void>(IPC.ACCEPT_INTRO_SUGGESTION, { videoId, startSeconds, endSeconds, confidence }),
  playVideo: (videoId: number) => invoke<PlaybackStartInfo>(IPC.PLAY_VIDEO, { videoId }),
  togglePause: () => invoke<void>(IPC.TOGGLE_PAUSE),
  seek: (positionSeconds: number) => invoke<void>(IPC.SEEK, { positionSeconds }),
  getCurrentPosition: () => invoke<number | null>(IPC.GET_CURRENT_POSITION),
  getDuration: () => invoke<number | null>(IPC.GET_DURATION),
  setVolume: (volume: number) => invoke<void>(IPC.SET_VOLUME, { volume }),
  getTracks: () => invoke<TrackMenu>(IPC.GET_TRACKS),
  setAudioTrack: (trackId: number) => invoke<void>(IPC.SET_AUDIO_TRACK, { trackId }),
  setSubtitleTrack: (trackId: number) => invoke<void>(IPC.SET_SUBTITLE_TRACK, { trackId }),
  getPreviewFrame: (seconds: number) => invoke<string | null>(IPC.GET_PREVIEW_FRAME, { seconds }),
  setPlaybackRate: (rate: number) => invoke<void>(IPC.SET_PLAYBACK_RATE, { rate }),
  setAudioDelay: (delayMs: number) => invoke<void>(IPC.SET_AUDIO_DELAY, { delayMs }),
  setSubtitleDelay: (delayMs: number) => invoke<void>(IPC.SET_SUBTITLE_DELAY, { delayMs }),
  setVideoWatched: (videoId: number, watched: boolean) => invoke<void>(IPC.SET_VIDEO_WATCHED, { videoId, watched }),
  removeLibraryRoot: (rootId: number) => invoke<void>(IPC.REMOVE_LIBRARY_ROOT, { rootId }),
  generateEpisodeThumbnails: (collectionId: number, force = false) => invoke<number>(IPC.GENERATE_EPISODE_THUMBNAILS, { collectionId, force }),
  cancelEpisodeThumbnails: () => invoke<void>(IPC.CANCEL_EPISODE_THUMBNAILS),
  generateEpisodeThumbnail: (videoId: number, force = false) => invoke<boolean>(IPC.GENERATE_EPISODE_THUMBNAIL, { videoId, force }),
  getEpisodeThumbnail: (videoId: number) => invoke<string | null>(IPC.GET_EPISODE_THUMBNAIL, { videoId }),
  setCollectionThumbnailsVisible: (collectionId: number, visible: boolean) => invoke<void>(IPC.SET_COLLECTION_THUMBNAILS_VISIBLE, { collectionId, visible }),
  stopPlayback: () => invoke<void>(IPC.STOP_PLAYBACK),
  removeVideoFromLibrary: (videoId: number) => invoke<void>(IPC.REMOVE_VIDEO_FROM_LIBRARY, { videoId }),
  deleteVideoFile: (videoId: number) => invoke<DeleteOutcome>(IPC.DELETE_VIDEO_FILE, { videoId }),
  removeCollectionFromLibrary: (collectionId: number) => invoke<void>(IPC.REMOVE_COLLECTION_FROM_LIBRARY, { collectionId }),
  deleteCollectionFiles: (collectionId: number) => invoke<DeleteOutcome>(IPC.DELETE_COLLECTION_FILES, { collectionId }),
  previewEpisodeNames: (collectionId: number) => invoke<EpisodeNamePlanItem[]>(IPC.PREVIEW_EPISODE_NAMES, { collectionId }),
  applyEpisodeNames: (collectionId: number) => invoke<number>(IPC.APPLY_EPISODE_NAMES, { collectionId }),
  setVideoDisplayName: (videoId: number, displayName: string) => invoke<void>(IPC.SET_VIDEO_DISPLAY_NAME, { videoId, displayName }),
  previewRename: (collectionId: number, pattern: string) => invoke<RenamePlanItem[]>(IPC.PREVIEW_RENAME, { collectionId, pattern }),
  applyRename: (collectionId: number, pattern: string) => invoke<RenameOutcome>(IPC.APPLY_RENAME, { collectionId, pattern }),
  setCollectionTitle: (collectionId: number, title: string) => invoke<void>(IPC.SET_COLLECTION_TITLE, { collectionId, title }),
  setCollectionType: (collectionId: number, collectionType: CollectionType) => invoke<void>(IPC.SET_COLLECTION_TYPE, { collectionId, collectionType }),
  mergeCollectionInto: (sourceId: number, targetId: number) => invoke<void>(IPC.MERGE_COLLECTION_INTO, { sourceId, targetId }),
  generateCollectionPoster: (collectionId: number, seconds: number) => invoke<string>(IPC.GENERATE_COLLECTION_POSTER, { collectionId, seconds }),
  getCollectionPoster: (collectionId: number) => invoke<string | null>(IPC.GET_COLLECTION_POSTER, { collectionId }),
  openPlayer: (videoId: number, collectionId: number) => invoke<void>(IPC.OPEN_PLAYER, { videoId, collectionId }),
  closePlayer: () => invoke<void>(IPC.CLOSE_PLAYER),
  setPlayerFullscreen: (enabled: boolean) => invoke<void>(IPC.SET_PLAYER_FULLSCREEN, { enabled }),
};
